# fly.toml app configuration file generated for mote on 2026-01-28T09:23:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mote'
primary_region = 'sjc'

[build]

[env]
  DATABASE_URL = 'file:/data/mote.db'
  NODE_ENV = 'production'
  UPLOADS_DIR = '/data/uploads'

[[mounts]]
  source = 'mote_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
